ALTER TABLE role ADD COLUMN role_level VARCHAR(20) NOT NULL DEFAULT 'WAREHOUSE';

UPDATE role SET role_level = 'SYSTEM' WHERE code = 'ADMINISTRATEUR';
UPDATE role SET role_level = 'STORE' WHERE code = 'RESPONSABLE_MAGASIN';
UPDATE role SET role_level = 'WAREHOUSE' WHERE code = 'RESPONSABLE_ENTREPOT';
